"""create_potion_images_table

Revision ID: a24bd462dd50
Revises: c90c7b7173fe
Create Date: 2025-04-24 19:03:46.757456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24bd462dd50'
down_revision = 'c90c7b7173fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potion_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potion_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potion_images')
    # ### end Alembic commands ###
