"""create_sword_galleries_table

Revision ID: 147c0d115fec
Revises: a24bd462dd50
Create Date: 2025-04-24 19:49:29.943572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147c0d115fec'
down_revision = 'a24bd462dd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sword_galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('magic_class', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sword_galleries')
    # ### end Alembic commands ###
