"""create_swords_table

Revision ID: 3eb1c267e034
Revises: 147c0d115fec
Create Date: 2025-04-24 19:55:56.947417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb1c267e034'
down_revision = '147c0d115fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('damage', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('mana_cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('element', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swords')
    # ### end Alembic commands ###
