"""create_potions_table

Revision ID: c90c7b7173fe
Revises: 0f9e5bdefa72
Create Date: 2025-04-24 18:56:30.314190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90c7b7173fe'
down_revision = '0f9e5bdefa72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potion_bag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('regeneration', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('element', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potions')
    # ### end Alembic commands ###
