"""add bank gold to adventure

Revision ID: 5582f238a3b8
Revises: 61ba87a28e2c
Create Date: 2025-11-28 16:48:04.106381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5582f238a3b8'
down_revision = '61ba87a28e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_gold', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure_states', schema=None) as batch_op:
        batch_op.drop_column('bank_gold')

    # ### end Alembic commands ###
