"""create_sword_images_table

Revision ID: b441dcdd3eb3
Revises: 3eb1c267e034
Create Date: 2025-04-24 20:02:24.709470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b441dcdd3eb3'
down_revision = '3eb1c267e034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sword_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sword_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sword_images')
    # ### end Alembic commands ###
