"""create_spells_table

Revision ID: d2d13b0bc0f8
Revises: d13e3fe46d01
Create Date: 2025-04-24 12:54:44.221138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d13b0bc0f8'
down_revision = 'd13e3fe46d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_book_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('damage', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('mana_cost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('element', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    # ### end Alembic commands ###
